name: Java CI with maven

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./dms
    
    steps:
      - uses: actions/checkout@v2
      - name: actions-setup-mysql
        uses: shogo82148/actions-setup-mysql@v1.7.0
        with:
          distribution: 'adopt'
          mysql-version: '8.0'
  
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Running the database
        run: mysql -uroot -h127.0.0.1 -e 'SELECT version()'
      - name: Building & Testing with Maven
        run: mvn test
        working-directory: ${{ env.working-directory }}
