name: Java CI with maven

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          working-directory: ./dms
          DB_DATABASE: test
          DB_USER: admin
          DB_PASSWORD: 'MansGotSQL-_-'
        ports:
          - '8888:3306'
    
    steps:
      - uses: actions/checkout@v2  
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -h localhost --port 8888 -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -e 'CREATE DATABASE IF NOT EXISTS test;'
      
      - name: Building & Testing with Maven
        run: |
          mvn clean install -X -Dmaven.test.skip
        working-directory: ${{ env.working-directory }}
