name: Java CI with maven

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./dms
      DB_DATABASE: test
      DB_USER: admin
      DB_PASSWORD: 'MansGotSQL-_-'
    
    steps:
      - uses: actions/checkout@v2  
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
      
      - name: Building & Testing with Maven
        run: |
          mvn clean install -X -Dmaven.test.skip
        working-directory: ${{ env.working-directory }}
