name: Java CI with maven

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          working-directory: ./dms
          DB_DATABASE: test
          DB_USER: admin
          DB_PASSWORD: 'MansGotSQL-_-'
        ports:
          - '8888:3306'
    
    steps:
      - uses: actions/checkout@v2  
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - uses: actions/checkout@v1
      - name: Setup MySQL
        run: |
          mysql -h 127.0.0.1 --port 3306 -u root -ppassword -e 'CREATE DATABASE IF NOT EXISTS test;'
      
      - name: Building & Testing with Maven
        run: |
          echo "Running maven stuff here :)"
        working-directory: ${{ env.working-directory }}
